drop table if exists posting CASCADE;
create table posting (
                         post_id bigint generated by default as identity,
                         title varchar(20),
                         content varchar(255),
                         name varchar(20),
                         primary key(post_id)
);